name: accounting-app
services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres_docker_init.sql:/docker-entrypoint-initdb.d/init.sql