### Get all api/v1/user
GET http://localhost:8080/api/v1/user/get-all
Accept: application/json

###

### Get user by ID
GET http://localhost:8080/api/v1/user/get/1
Accept: application/json

###

### Create new user
POST http://localhost:8080/api/v1/user/create
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe",
  "password": "securePass123",
  "full_name": "John Doe"
}

###

### Update existing user
PUT http://localhost:8080/api/v1/user/update/1
Content-Type: application/json
Accept: application/json

{
  "username": "john_updated",
  "full_name": "John Updated"
}
