spring:
  application:
    name: AccountingApp
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting_db
    username: postgres
    password: 1234
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml